# ./pyproject.toml
[project]
name = "dev-platform"
version = "0.1.0"
description = ""
authors = [
    {name = "Sergio Pereira",email = "sergiopereira.br@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "pymysql (>=1.1.1,<2.0.0)",
    "aiomysql (>=0.2.0,<0.3.0)",
    "typer (>=0.15.4,<0.16.0)",
    "pydantic[email] (>=2.11.7,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "uuid (>=1.30,<2.0)",
    "alembic (>=1.16.1,<2.0.0)",
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "pandas (>=2.3.0,<3.0.0)",
    "cryptography (>=45.0.4,<46.0.0)",
    "pydantic-settings (>=2.9.1,<3.0.0)",
]

[tool.poetry]
packages = [{include = "dev_platform", from = "src"}]

[tool.poetry.group.dev.dependencies]
black = "^23.0"
flake8 = "^6.0"
taskipy = "^1.14.1"
reportlab = "^4.4.1"
chardet = "^5.2.0"
pypandoc = "^1.15"
mypy = "^1.16.0"
pytest-asyncio = "^1.0.0"
types-reportlab = "^4.4.1.20250602"
matplotlib = "^3.10.3"
numpy = "^2.3.0"
python-dateutil = "^2.9.0.post0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
pymdown-extensions = "^10.15"
mkdocstrings = "^0.29.1"
mkdocstrings-python = "^1.16.10"
sphinx = "^6.0"
sphinx-rtd-theme = "^1.0"
mkdocs-material = "^9.6.14"


[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

# Configuração opcional para definir o script principal
[tool.poetry.scripts]
dev-platform = "dev_platform.main:main"  # Isso cria um comando executável
docs-serve = "mkdocs:serve"  # Iniciar servidor de documentação local
docs-build = "mkdocs:build"  # Construir a documentação estática

[tool.taskipy.tasks]
# Definição de tarefas para o projeto
format = "poetry run black ./src ./tests ./scripts"
lint = "poetry run flake8 ./src ./tests ./scripts"
test = "poetry run pytest --cov=dev_platform --cov-report=html --cov-report=term ./tests"
test-async = "poetry run pytest-asyncio --cov=dev_platform --cov-report=html --cov-report=term ./tests"
docs-serve = "poetry run mkdocs serve"  # Iniciar servidor de documentação local
docs-build = "poetry run mkdocs build"  # Construir a documentação estática 
docs-serve-live = "poetry run mkdocs serve --livereload"  # Iniciar servidor de documentação com recarregamento automático
docs-serve-live-port = "poetry run mkdocs serve --livereload --dev-addr 0.0.0.0:8000"

# Tarefas para gerenciamento de usuários - testes e desenvolvimento
list = "poetry run python ./src/dev_platform/main.py user list-users"
list_debug = "poetry run python -m debugpy --listen 5678 --wait-for-client ./src/dev_platform/main.py user list-users"
create = "poetry run python ./src/dev_platform/main.py user create-user --name \"Sergio da Silva Pereira\" --email sergio.hertz@gmail.com"
delete = "poetry run python ./src/dev_platform/main.py user delete-user --email 'sergiopereira.br@hotmail.com'"
update = "poetry run python ./src/dev_platform/main.py user update-user --email 'sergiopereira.br@hotmail.com' --name 'Sergio P.'"

# Tarefas gerenciamento de usuários
list_users = "poetry run python ./src/dev_platform/main.py user list-users"
create_user = "poetry run python ./src/dev_platform/main.py user create-user --name 'Sergio da Silva Pereira' --email 'sergio.hertz@gmail.com'"
delete_user = "poetry run python ./src/dev_platform/main.py user delete-user --email 'sergiopereira.br@hotmail.com'"
update_user = "poetry run python ./src/dev_platform/main.py user update-user --email 'sergiopereira.br@hotmail.com' --name 'Sergio P.'"

# Tarefas para gerenciamento de projetos - testes e desenvolvimento
list_projects = "poetry run python ./src/dev_platform/main.py project list-projects"
create_project = "poetry run python ./src/dev_platform/main.py project create-project --name 'Projeto Teste' --description 'Descrição do Projeto Teste'"
delete_project = "poetry run python ./src/dev_platform/main.py project delete-project --name 'Projeto Teste'"
update_project = "poetry run python ./src/dev_platform/main.py project update-project --name 'Projeto Teste' --description 'Descrição Atualizada do Projeto Teste'"

# Tarefas para manipulação de arquivos e geração de relatórios
clean = "pwsh -Command ./scripts/tools/del_folderes.ps1 './src' '__pycache__'"
stack = "pwsh -Command ./scripts/tools/stack_files.ps1 './src' 'py'"
stack2pdf = "poetry run python ./scripts/tools/pdf_generator.py ./src/stake_file --title \"Arquivos do Projeto DEV Platform\" -v"
compilado = "poetry run python ./scripts/tools/pdf_generator.py ./src/stake_file --title \"Arquivos do Projeto DEV Platform\" -v"

# Tarefas para conversão de arquivos Markdown para Word
# (melhor executar no WSL Ubuntu 20.04)
analise_md2word = "poetry run python ./scripts/tools/md_to_word.py ./docs/análise_26.md"
onboarding_md2word = "poetry run python ./scripts/tools/md_to_word.py ./docs/onboarding_26.md"

# Tarefas para análise de logs
analisa_log = "poetry run python ./scripts/tools/log_analyzer_mvp.py --log_folder_path ./scripts/requisitos_log"

[tool.mypy]
python_version = "3.11"
plugins = "pydantic.mypy"
